Object subclass: #Behavior
	instanceVariableNames: 'name instanceSize methods superClass variables classVariables poolDictionaries category'
	classVariableNames: ''
	poolDictionaries: ''
	category: ''
!

Behavior subclass: #Class
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: ''!

!Class methodsFor: ''!
	scuzzleBud
		'Dodi'
	!
	getSuperVar
		name
	! !
